// 化學式校準題庫：只保存經人工挑選的中學常見物質。
// s: j = 國中核心、s = 高中常見、a = 高中進階
// i: 陽離子符號:電荷:數量 | 陰離子符號:電荷:數量
window.CHEM_FORMULA_DATA = (() => {
    const M = (f, n, s, g, extra = {}) => ({ f, n, s, g, kind: extra.kind || 'molecular', ...extra });
    const I = (f, n, s, g, cs, cq, cc, as, aq, ac, extra = {}) => ({
        f, n, s, g, kind: extra.kind || 'ionic',
        ions: { cation: { symbol: cs, charge: cq, count: cc }, anion: { symbol: as, charge: aq, count: ac } },
        ...extra
    });

    return [
        // 國中與基礎高中：單質、常見分子、氧化物與酸
        M('H2', '氫', 'j', 'element'), M('N2', '氮', 'j', 'element'), M('O2', '氧', 'j', 'element'),
        M('F2', '氟', 's', 'element'), M('Cl2', '氯', 'j', 'element'), M('Br2', '溴', 's', 'element'),
        M('I2', '碘', 'j', 'element'), M('O3', '臭氧', 'j', 'element'), M('P4', '磷', 's', 'element'),
        M('S8', '硫', 's', 'element'), M('H2O', '水', 'j', 'molecule'), M('H2O2', '過氧化氫', 'j', 'peroxide'),
        M('NH3', '氨', 'j', 'molecule'), M('HF', '氟化氫', 's', 'acid'), M('HCl', '氯化氫', 'j', 'acid'),
        M('HBr', '溴化氫', 's', 'acid'), M('HI', '碘化氫', 's', 'acid'), M('H2S', '硫化氫', 's', 'acid'),
        M('CO', '一氧化碳', 'j', 'oxide'), M('CO2', '二氧化碳', 'j', 'oxide'), M('NO', '一氧化氮', 's', 'oxide'),
        M('NO2', '二氧化氮', 'j', 'oxide'), M('N2O', '一氧化二氮', 's', 'oxide'), M('N2O3', '三氧化二氮', 'a', 'oxide'),
        M('N2O4', '四氧化二氮', 'a', 'oxide'), M('N2O5', '五氧化二氮', 's', 'oxide'), M('SO2', '二氧化硫', 'j', 'oxide'),
        M('SO3', '三氧化硫', 's', 'oxide'), M('P2O5', '五氧化二磷', 's', 'oxide'), M('SiO2', '二氧化矽', 'j', 'oxide'),
        M('TiO2', '二氧化鈦', 's', 'oxide'), M('HNO3', '硝酸', 'j', 'acid'), M('HNO2', '亞硝酸', 's', 'acid'),
        M('H2SO4', '硫酸', 'j', 'acid'), M('H2SO3', '亞硫酸', 's', 'acid'), M('H2CO3', '碳酸', 'j', 'acid'),
        M('H3PO4', '磷酸', 'j', 'acid'), M('HClO4', '過氯酸', 'a', 'oxyacid'), M('HClO3', '氯酸', 'a', 'oxyacid'),
        M('HClO2', '亞氯酸', 'a', 'oxyacid'), M('HClO', '次氯酸', 'a', 'oxyacid'), M('CH3COOH', '醋酸', 's', 'acetate'),
        M('H2C2O4', '草酸', 's', 'acid'),

        // 氯化物、鹵化物與氟化物
        I('LiCl', '氯化鋰', 'j', 'halide', 'Li', 1, 1, 'Cl', -1, 1),
        I('NaCl', '氯化鈉', 'j', 'halide', 'Na', 1, 1, 'Cl', -1, 1),
        I('KCl', '氯化鉀', 'j', 'halide', 'K', 1, 1, 'Cl', -1, 1),
        I('MgCl2', '氯化鎂', 'j', 'halide', 'Mg', 2, 1, 'Cl', -1, 2),
        I('CaCl2', '氯化鈣', 'j', 'halide', 'Ca', 2, 1, 'Cl', -1, 2),
        I('SrCl2', '氯化鍶', 's', 'halide', 'Sr', 2, 1, 'Cl', -1, 2),
        I('BaCl2', '氯化鋇', 's', 'halide', 'Ba', 2, 1, 'Cl', -1, 2),
        I('AlCl3', '氯化鋁', 'j', 'halide', 'Al', 3, 1, 'Cl', -1, 3),
        I('ZnCl2', '氯化鋅', 's', 'halide', 'Zn', 2, 1, 'Cl', -1, 2),
        I('AgCl', '氯化銀', 's', 'halide', 'Ag', 1, 1, 'Cl', -1, 1),
        I('NH4Cl', '氯化銨', 'j', 'halide', 'NH4', 1, 1, 'Cl', -1, 1),
        I('PbCl2', '氯化鉛', 's', 'halide', 'Pb', 2, 1, 'Cl', -1, 2),
        I('CuCl', '氯化亞銅', 'a', 'variable', 'Cu', 1, 1, 'Cl', -1, 1),
        I('CuCl2', '氯化銅', 's', 'variable', 'Cu', 2, 1, 'Cl', -1, 2),
        I('FeCl2', '氯化亞鐵', 's', 'variable', 'Fe', 2, 1, 'Cl', -1, 2),
        I('FeCl3', '氯化鐵', 's', 'variable', 'Fe', 3, 1, 'Cl', -1, 3),
        I('SnCl2', '氯化亞錫', 'a', 'variable', 'Sn', 2, 1, 'Cl', -1, 2),
        I('SnCl4', '氯化錫', 'a', 'variable', 'Sn', 4, 1, 'Cl', -1, 4),
        I('LiF', '氟化鋰', 's', 'halide', 'Li', 1, 1, 'F', -1, 1),
        I('NaF', '氟化鈉', 'j', 'halide', 'Na', 1, 1, 'F', -1, 1),
        I('KF', '氟化鉀', 's', 'halide', 'K', 1, 1, 'F', -1, 1),
        I('MgF2', '氟化鎂', 's', 'halide', 'Mg', 2, 1, 'F', -1, 2),
        I('CaF2', '氟化鈣', 'j', 'halide', 'Ca', 2, 1, 'F', -1, 2),
        I('AlF3', '氟化鋁', 's', 'halide', 'Al', 3, 1, 'F', -1, 3),
        I('NH4F', '氟化銨', 'a', 'halide', 'NH4', 1, 1, 'F', -1, 1),
        I('NaBr', '溴化鈉', 's', 'halide', 'Na', 1, 1, 'Br', -1, 1),
        I('KBr', '溴化鉀', 's', 'halide', 'K', 1, 1, 'Br', -1, 1),
        I('CaBr2', '溴化鈣', 's', 'halide', 'Ca', 2, 1, 'Br', -1, 2),
        I('AgBr', '溴化銀', 's', 'halide', 'Ag', 1, 1, 'Br', -1, 1),
        I('PbBr2', '溴化鉛', 'a', 'halide', 'Pb', 2, 1, 'Br', -1, 2),
        I('NaI', '碘化鈉', 's', 'halide', 'Na', 1, 1, 'I', -1, 1),
        I('KI', '碘化鉀', 's', 'halide', 'K', 1, 1, 'I', -1, 1),
        I('AgI', '碘化銀', 's', 'halide', 'Ag', 1, 1, 'I', -1, 1),
        I('PbI2', '碘化鉛', 's', 'halide', 'Pb', 2, 1, 'I', -1, 2),

        // 氧化物
        I('Li2O', '氧化鋰', 's', 'oxide', 'Li', 1, 2, 'O', -2, 1),
        I('Na2O', '氧化鈉', 'j', 'oxide', 'Na', 1, 2, 'O', -2, 1),
        I('K2O', '氧化鉀', 's', 'oxide', 'K', 1, 2, 'O', -2, 1),
        I('MgO', '氧化鎂', 'j', 'oxide', 'Mg', 2, 1, 'O', -2, 1),
        I('CaO', '氧化鈣', 'j', 'oxide', 'Ca', 2, 1, 'O', -2, 1),
        I('BaO', '氧化鋇', 's', 'oxide', 'Ba', 2, 1, 'O', -2, 1),
        I('Al2O3', '氧化鋁', 'j', 'oxide', 'Al', 3, 2, 'O', -2, 3),
        I('ZnO', '氧化鋅', 's', 'oxide', 'Zn', 2, 1, 'O', -2, 1),
        I('Ag2O', '氧化銀', 's', 'oxide', 'Ag', 1, 2, 'O', -2, 1),
        I('Cu2O', '氧化亞銅', 's', 'variable', 'Cu', 1, 2, 'O', -2, 1),
        I('CuO', '氧化銅', 'j', 'variable', 'Cu', 2, 1, 'O', -2, 1),
        I('FeO', '氧化亞鐵', 's', 'variable', 'Fe', 2, 1, 'O', -2, 1),
        I('Fe2O3', '氧化鐵', 'j', 'variable', 'Fe', 3, 2, 'O', -2, 3),
        M('Fe3O4', '四氧化三鐵', 's', 'mixed-oxide', { kind: 'mixed' }),
        I('SnO', '氧化亞錫', 'a', 'variable', 'Sn', 2, 1, 'O', -2, 1),
        I('SnO2', '氧化錫', 'a', 'variable', 'Sn', 4, 1, 'O', -2, 2),
        I('PbO', '氧化鉛', 's', 'variable', 'Pb', 2, 1, 'O', -2, 1),
        I('PbO2', '二氧化鉛', 'a', 'variable', 'Pb', 4, 1, 'O', -2, 2),
        I('Cr2O3', '氧化鉻', 'a', 'variable', 'Cr', 3, 2, 'O', -2, 3),
        M('CrO3', '三氧化鉻', 'a', 'oxide'), M('MnO2', '二氧化錳', 'j', 'oxide'),

        // 氫氧化物
        I('LiOH', '氫氧化鋰', 's', 'hydroxide', 'Li', 1, 1, 'OH', -1, 1),
        I('NaOH', '氫氧化鈉', 'j', 'hydroxide', 'Na', 1, 1, 'OH', -1, 1),
        I('KOH', '氫氧化鉀', 'j', 'hydroxide', 'K', 1, 1, 'OH', -1, 1),
        I('Mg(OH)2', '氫氧化鎂', 'j', 'hydroxide', 'Mg', 2, 1, 'OH', -1, 2),
        I('Ca(OH)2', '氫氧化鈣', 'j', 'hydroxide', 'Ca', 2, 1, 'OH', -1, 2),
        I('Sr(OH)2', '氫氧化鍶', 's', 'hydroxide', 'Sr', 2, 1, 'OH', -1, 2),
        I('Ba(OH)2', '氫氧化鋇', 's', 'hydroxide', 'Ba', 2, 1, 'OH', -1, 2),
        I('Al(OH)3', '氫氧化鋁', 'j', 'hydroxide', 'Al', 3, 1, 'OH', -1, 3),
        I('Zn(OH)2', '氫氧化鋅', 's', 'hydroxide', 'Zn', 2, 1, 'OH', -1, 2),
        I('Cu(OH)2', '氫氧化銅', 'j', 'hydroxide', 'Cu', 2, 1, 'OH', -1, 2),
        I('Fe(OH)2', '氫氧化亞鐵', 's', 'variable', 'Fe', 2, 1, 'OH', -1, 2),
        I('Fe(OH)3', '氫氧化鐵', 's', 'variable', 'Fe', 3, 1, 'OH', -1, 3),
        I('Sn(OH)2', '氫氧化亞錫', 'a', 'variable', 'Sn', 2, 1, 'OH', -1, 2),
        I('Pb(OH)2', '氫氧化鉛', 'a', 'variable', 'Pb', 2, 1, 'OH', -1, 2),
        I('Cr(OH)3', '氫氧化鉻', 'a', 'hydroxide', 'Cr', 3, 1, 'OH', -1, 3),

        // 硝酸鹽與亞硝酸鹽
        I('LiNO3', '硝酸鋰', 's', 'nitrate', 'Li', 1, 1, 'NO3', -1, 1),
        I('NaNO3', '硝酸鈉', 'j', 'nitrate', 'Na', 1, 1, 'NO3', -1, 1),
        I('KNO3', '硝酸鉀', 'j', 'nitrate', 'K', 1, 1, 'NO3', -1, 1),
        I('Mg(NO3)2', '硝酸鎂', 's', 'nitrate', 'Mg', 2, 1, 'NO3', -1, 2),
        I('Ca(NO3)2', '硝酸鈣', 'j', 'nitrate', 'Ca', 2, 1, 'NO3', -1, 2),
        I('Ba(NO3)2', '硝酸鋇', 's', 'nitrate', 'Ba', 2, 1, 'NO3', -1, 2),
        I('Al(NO3)3', '硝酸鋁', 's', 'nitrate', 'Al', 3, 1, 'NO3', -1, 3),
        I('Zn(NO3)2', '硝酸鋅', 's', 'nitrate', 'Zn', 2, 1, 'NO3', -1, 2),
        I('AgNO3', '硝酸銀', 'j', 'nitrate', 'Ag', 1, 1, 'NO3', -1, 1),
        I('NH4NO3', '硝酸銨', 'j', 'nitrate', 'NH4', 1, 1, 'NO3', -1, 1),
        I('Cu(NO3)2', '硝酸銅', 's', 'nitrate', 'Cu', 2, 1, 'NO3', -1, 2),
        I('Fe(NO3)2', '硝酸亞鐵', 'a', 'variable', 'Fe', 2, 1, 'NO3', -1, 2),
        I('Fe(NO3)3', '硝酸鐵', 'a', 'variable', 'Fe', 3, 1, 'NO3', -1, 3),
        I('Pb(NO3)2', '硝酸鉛', 's', 'nitrate', 'Pb', 2, 1, 'NO3', -1, 2),
        I('Sn(NO3)2', '硝酸亞錫', 'a', 'variable', 'Sn', 2, 1, 'NO3', -1, 2),
        I('NaNO2', '亞硝酸鈉', 's', 'nitrite', 'Na', 1, 1, 'NO2', -1, 1),
        I('KNO2', '亞硝酸鉀', 's', 'nitrite', 'K', 1, 1, 'NO2', -1, 1),
        I('NH4NO2', '亞硝酸銨', 'a', 'nitrite', 'NH4', 1, 1, 'NO2', -1, 1),
        I('AgNO2', '亞硝酸銀', 'a', 'nitrite', 'Ag', 1, 1, 'NO2', -1, 1),

        // 硫酸鹽、亞硫酸鹽與酸式根
        I('Na2SO4', '硫酸鈉', 'j', 'sulfate', 'Na', 1, 2, 'SO4', -2, 1),
        I('K2SO4', '硫酸鉀', 's', 'sulfate', 'K', 1, 2, 'SO4', -2, 1),
        I('MgSO4', '硫酸鎂', 'j', 'sulfate', 'Mg', 2, 1, 'SO4', -2, 1),
        I('CaSO4', '硫酸鈣', 'j', 'sulfate', 'Ca', 2, 1, 'SO4', -2, 1),
        I('BaSO4', '硫酸鋇', 's', 'sulfate', 'Ba', 2, 1, 'SO4', -2, 1),
        I('Al2(SO4)3', '硫酸鋁', 's', 'sulfate', 'Al', 3, 2, 'SO4', -2, 3),
        I('ZnSO4', '硫酸鋅', 's', 'sulfate', 'Zn', 2, 1, 'SO4', -2, 1),
        I('CuSO4', '硫酸銅', 'j', 'sulfate', 'Cu', 2, 1, 'SO4', -2, 1),
        I('FeSO4', '硫酸亞鐵', 's', 'variable', 'Fe', 2, 1, 'SO4', -2, 1),
        I('Fe2(SO4)3', '硫酸鐵', 's', 'variable', 'Fe', 3, 2, 'SO4', -2, 3),
        I('(NH4)2SO4', '硫酸銨', 'j', 'sulfate', 'NH4', 1, 2, 'SO4', -2, 1),
        I('Ag2SO4', '硫酸銀', 'a', 'sulfate', 'Ag', 1, 2, 'SO4', -2, 1),
        I('PbSO4', '硫酸鉛', 's', 'sulfate', 'Pb', 2, 1, 'SO4', -2, 1),
        I('MnSO4', '硫酸錳', 's', 'sulfate', 'Mn', 2, 1, 'SO4', -2, 1),
        I('NiSO4', '硫酸鎳', 'a', 'sulfate', 'Ni', 2, 1, 'SO4', -2, 1),
        I('CoSO4', '硫酸亞鈷', 'a', 'variable', 'Co', 2, 1, 'SO4', -2, 1),
        I('SnSO4', '硫酸亞錫', 'a', 'variable', 'Sn', 2, 1, 'SO4', -2, 1),
        I('Na2SO3', '亞硫酸鈉', 's', 'sulfite', 'Na', 1, 2, 'SO3', -2, 1),
        I('K2SO3', '亞硫酸鉀', 'a', 'sulfite', 'K', 1, 2, 'SO3', -2, 1),
        I('CaSO3', '亞硫酸鈣', 's', 'sulfite', 'Ca', 2, 1, 'SO3', -2, 1),
        I('NaHSO3', '亞硫酸氫鈉', 'a', 'sulfite-acid', 'Na', 1, 1, 'HSO3', -1, 1),
        I('NaHSO4', '硫酸氫鈉', 'a', 'sulfate-acid', 'Na', 1, 1, 'HSO4', -1, 1),

        // 碳酸鹽、碳酸氫鹽與磷酸鹽
        I('Li2CO3', '碳酸鋰', 's', 'carbonate', 'Li', 1, 2, 'CO3', -2, 1),
        I('Na2CO3', '碳酸鈉', 'j', 'carbonate', 'Na', 1, 2, 'CO3', -2, 1),
        I('K2CO3', '碳酸鉀', 'j', 'carbonate', 'K', 1, 2, 'CO3', -2, 1),
        I('MgCO3', '碳酸鎂', 'j', 'carbonate', 'Mg', 2, 1, 'CO3', -2, 1),
        I('CaCO3', '碳酸鈣', 'j', 'carbonate', 'Ca', 2, 1, 'CO3', -2, 1),
        I('BaCO3', '碳酸鋇', 's', 'carbonate', 'Ba', 2, 1, 'CO3', -2, 1),
        I('ZnCO3', '碳酸鋅', 's', 'carbonate', 'Zn', 2, 1, 'CO3', -2, 1),
        I('CuCO3', '碳酸銅', 'a', 'carbonate', 'Cu', 2, 1, 'CO3', -2, 1),
        I('FeCO3', '碳酸亞鐵', 'a', 'variable', 'Fe', 2, 1, 'CO3', -2, 1),
        I('(NH4)2CO3', '碳酸銨', 's', 'carbonate', 'NH4', 1, 2, 'CO3', -2, 1),
        I('NaHCO3', '碳酸氫鈉', 'j', 'carbonate-acid', 'Na', 1, 1, 'HCO3', -1, 1),
        I('KHCO3', '碳酸氫鉀', 's', 'carbonate-acid', 'K', 1, 1, 'HCO3', -1, 1),
        I('Ca(HCO3)2', '碳酸氫鈣', 's', 'carbonate-acid', 'Ca', 2, 1, 'HCO3', -1, 2),
        I('Na3PO4', '磷酸鈉', 's', 'phosphate', 'Na', 1, 3, 'PO4', -3, 1),
        I('K3PO4', '磷酸鉀', 's', 'phosphate', 'K', 1, 3, 'PO4', -3, 1),
        I('Ca3(PO4)2', '磷酸鈣', 'j', 'phosphate', 'Ca', 2, 3, 'PO4', -3, 2),
        I('AlPO4', '磷酸鋁', 's', 'phosphate', 'Al', 3, 1, 'PO4', -3, 1),
        I('Mg3(PO4)2', '磷酸鎂', 's', 'phosphate', 'Mg', 2, 3, 'PO4', -3, 2),
        I('(NH4)3PO4', '磷酸銨', 's', 'phosphate', 'NH4', 1, 3, 'PO4', -3, 1),
        I('Na2HPO4', '磷酸氫二鈉', 'a', 'phosphate-acid', 'Na', 1, 2, 'HPO4', -2, 1),
        I('NaH2PO4', '磷酸二氫鈉', 'a', 'phosphate-acid', 'Na', 1, 1, 'H2PO4', -1, 1),
        I('KH2PO4', '磷酸二氫鉀', 'a', 'phosphate-acid', 'K', 1, 1, 'H2PO4', -1, 1),
        I('K2HPO4', '磷酸氫二鉀', 'a', 'phosphate-acid', 'K', 1, 2, 'HPO4', -2, 1),

        // 醋酸鹽、草酸鹽與硫代硫酸鹽
        I('CH3COONa', '醋酸鈉', 's', 'acetate', 'Na', 1, 1, 'CH3COO', -1, 1),
        I('CH3COOK', '醋酸鉀', 's', 'acetate', 'K', 1, 1, 'CH3COO', -1, 1),
        I('CH3COONH4', '醋酸銨', 's', 'acetate', 'NH4', 1, 1, 'CH3COO', -1, 1),
        I('Ca(CH3COO)2', '醋酸鈣', 's', 'acetate', 'Ca', 2, 1, 'CH3COO', -1, 2),
        I('Mg(CH3COO)2', '醋酸鎂', 'a', 'acetate', 'Mg', 2, 1, 'CH3COO', -1, 2),
        I('Cu(CH3COO)2', '醋酸銅', 'a', 'acetate', 'Cu', 2, 1, 'CH3COO', -1, 2),
        I('Pb(CH3COO)2', '醋酸鉛', 'a', 'acetate', 'Pb', 2, 1, 'CH3COO', -1, 2),
        I('Al(CH3COO)3', '醋酸鋁', 'a', 'acetate', 'Al', 3, 1, 'CH3COO', -1, 3),
        I('Na2C2O4', '草酸鈉', 's', 'oxalate', 'Na', 1, 2, 'C2O4', -2, 1),
        I('K2C2O4', '草酸鉀', 's', 'oxalate', 'K', 1, 2, 'C2O4', -2, 1),
        I('CaC2O4', '草酸鈣', 's', 'oxalate', 'Ca', 2, 1, 'C2O4', -2, 1),
        I('FeC2O4', '草酸亞鐵', 'a', 'oxalate', 'Fe', 2, 1, 'C2O4', -2, 1),
        I('Na2S2O3', '硫代硫酸鈉', 's', 'thiosulfate', 'Na', 1, 2, 'S2O3', -2, 1),
        I('K2S2O3', '硫代硫酸鉀', 'a', 'thiosulfate', 'K', 1, 2, 'S2O3', -2, 1),
        I('(NH4)2S2O3', '硫代硫酸銨', 'a', 'thiosulfate', 'NH4', 1, 2, 'S2O3', -2, 1),

        // 硫化物與其他常見離子化合物
        I('Na2S', '硫化鈉', 's', 'sulfide', 'Na', 1, 2, 'S', -2, 1),
        I('K2S', '硫化鉀', 's', 'sulfide', 'K', 1, 2, 'S', -2, 1),
        I('MgS', '硫化鎂', 's', 'sulfide', 'Mg', 2, 1, 'S', -2, 1),
        I('CaS', '硫化鈣', 's', 'sulfide', 'Ca', 2, 1, 'S', -2, 1),
        I('Al2S3', '硫化鋁', 's', 'sulfide', 'Al', 3, 2, 'S', -2, 3),
        I('FeS', '硫化亞鐵', 's', 'variable', 'Fe', 2, 1, 'S', -2, 1),
        I('Fe2S3', '硫化鐵', 'a', 'variable', 'Fe', 3, 2, 'S', -2, 3),
        I('Cu2S', '硫化亞銅', 'a', 'variable', 'Cu', 1, 2, 'S', -2, 1),
        I('CuS', '硫化銅', 's', 'variable', 'Cu', 2, 1, 'S', -2, 1),
        I('ZnS', '硫化鋅', 's', 'sulfide', 'Zn', 2, 1, 'S', -2, 1),
        I('PbS', '硫化鉛', 'a', 'sulfide', 'Pb', 2, 1, 'S', -2, 1),
        I('Na2O2', '過氧化鈉', 's', 'peroxide', 'Na', 1, 2, 'O2', -2, 1),
        I('BaO2', '過氧化鋇', 'a', 'peroxide', 'Ba', 2, 1, 'O2', -2, 1),
        I('CaC2', '碳化鈣', 's', 'carbide', 'Ca', 2, 1, 'C2', -2, 1),

        // 鉻酸鹽、重鉻酸鹽、錳酸鹽與過錳酸鹽
        I('K2CrO4', '鉻酸鉀', 'a', 'chromate', 'K', 1, 2, 'CrO4', -2, 1),
        I('Na2CrO4', '鉻酸鈉', 'a', 'chromate', 'Na', 1, 2, 'CrO4', -2, 1),
        I('BaCrO4', '鉻酸鋇', 'a', 'chromate', 'Ba', 2, 1, 'CrO4', -2, 1),
        I('PbCrO4', '鉻酸鉛', 'a', 'chromate', 'Pb', 2, 1, 'CrO4', -2, 1),
        I('Ag2CrO4', '鉻酸銀', 'a', 'chromate', 'Ag', 1, 2, 'CrO4', -2, 1),
        I('K2Cr2O7', '重鉻酸鉀', 'a', 'dichromate', 'K', 1, 2, 'Cr2O7', -2, 1),
        I('Na2Cr2O7', '重鉻酸鈉', 'a', 'dichromate', 'Na', 1, 2, 'Cr2O7', -2, 1),
        I('(NH4)2Cr2O7', '重鉻酸銨', 'a', 'dichromate', 'NH4', 1, 2, 'Cr2O7', -2, 1),
        I('KMnO4', '過錳酸鉀', 'a', 'permanganate', 'K', 1, 1, 'MnO4', -1, 1),
        I('NaMnO4', '過錳酸鈉', 'a', 'permanganate', 'Na', 1, 1, 'MnO4', -1, 1),
        I('K2MnO4', '錳酸鉀', 'a', 'manganate', 'K', 1, 2, 'MnO4', -2, 1),
        I('Na2MnO4', '錳酸鈉', 'a', 'manganate', 'Na', 1, 2, 'MnO4', -2, 1),

        // 次、亞、正、過氯酸鹽系列
        I('NaClO', '次氯酸鈉', 's', 'hypochlorite', 'Na', 1, 1, 'ClO', -1, 1),
        I('KClO', '次氯酸鉀', 'a', 'hypochlorite', 'K', 1, 1, 'ClO', -1, 1),
        I('Ca(ClO)2', '次氯酸鈣', 's', 'hypochlorite', 'Ca', 2, 1, 'ClO', -1, 2),
        I('NaClO2', '亞氯酸鈉', 'a', 'chlorite', 'Na', 1, 1, 'ClO2', -1, 1),
        I('KClO2', '亞氯酸鉀', 'a', 'chlorite', 'K', 1, 1, 'ClO2', -1, 1),
        I('NaClO3', '氯酸鈉', 's', 'chlorate', 'Na', 1, 1, 'ClO3', -1, 1),
        I('KClO3', '氯酸鉀', 's', 'chlorate', 'K', 1, 1, 'ClO3', -1, 1),
        I('KClO4', '過氯酸鉀', 'a', 'perchlorate', 'K', 1, 1, 'ClO4', -1, 1),
        I('NaClO4', '過氯酸鈉', 'a', 'perchlorate', 'Na', 1, 1, 'ClO4', -1, 1),
        I('NH4ClO4', '過氯酸銨', 'a', 'perchlorate', 'NH4', 1, 1, 'ClO4', -1, 1),
        I('KIO3', '碘酸鉀', 'a', 'iodate', 'K', 1, 1, 'IO3', -1, 1),
        I('NaIO3', '碘酸鈉', 'a', 'iodate', 'Na', 1, 1, 'IO3', -1, 1),

        // 水合物、複鹽與常見實驗物質
        I('CuSO4·5H2O', '五水合硫酸銅', 's', 'hydrate', 'Cu', 2, 1, 'SO4', -2, 1, { kind: 'hydrate' }),
        I('Na2CO3·10H2O', '十水合碳酸鈉', 'a', 'hydrate', 'Na', 1, 2, 'CO3', -2, 1, { kind: 'hydrate' }),
        I('CaSO4·2H2O', '二水合硫酸鈣', 's', 'hydrate', 'Ca', 2, 1, 'SO4', -2, 1, { kind: 'hydrate' }),
        I('FeSO4·7H2O', '七水合硫酸亞鐵', 'a', 'hydrate', 'Fe', 2, 1, 'SO4', -2, 1, { kind: 'hydrate' }),
        I('MgSO4·7H2O', '七水合硫酸鎂', 's', 'hydrate', 'Mg', 2, 1, 'SO4', -2, 1, { kind: 'hydrate' }),
        I('CoCl2·6H2O', '六水合氯化亞鈷', 'a', 'hydrate', 'Co', 2, 1, 'Cl', -1, 2, { kind: 'hydrate' }),
        M('KAl(SO4)2·12H2O', '十二水合硫酸鋁鉀', 'a', 'double-salt', { kind: 'complex' }),
        M('(NH4)2Fe(SO4)2·6H2O', '六水合硫酸亞鐵銨', 'a', 'double-salt', { kind: 'complex' }),
        M('KHC8H4O4', '鄰苯二甲酸氫鉀', 'a', 'standard-substance', { kind: 'complex' }),
        M('KSCN', '硫氰酸鉀', 's', 'reagent', { kind: 'complex' }),
        I('Na2S2O3·5H2O', '五水合硫代硫酸鈉', 's', 'hydrate', 'Na', 1, 2, 'S2O3', -2, 1, { kind: 'hydrate' })
    ];
})();
