const SUBSTANCE_LIST = [
    // --- 離子晶體 (獨立列出基本單元與晶體堆積) ---
    { 
        formula: "NaCl", 
        name: "氯化鈉 (基本單元)", 
        common: "食鹽", 
        category: "離子晶體", 
        key: "NaCl|Simple|基本單元 (離子對)", 
        tags: ["NaCl", "氯化鈉", "食鹽", "離子對"] 
    },
    { 
        formula: "NaCl", 
        name: "氯化鈉 (晶體堆積)", 
        common: "食鹽", 
        category: "離子晶體", 
        key: "NaCl|Crystal|晶體堆積 (FCC)", 
        tags: ["NaCl", "氯化鈉", "食鹽", "面心立方", "FCC"] 
    },
    { 
        formula: "CsCl", 
        name: "氯化銫 (基本單元)", 
        common: "", 
        category: "離子晶體", 
        key: "CsCl|Simple|基本單元 (離子對)", 
        tags: ["CsCl", "氯化銫", "離子對"] 
    },
    { 
        formula: "CsCl", 
        name: "氯化銫 (晶體堆積)", 
        common: "", 
        category: "離子晶體", 
        key: "CsCl|Crystal|晶體堆積 (SC)", 
        tags: ["CsCl", "氯化銫", "簡單立方", "SC"] 
    },
    { 
        formula: "ZnS", 
        name: "硫化鋅 (基本單元)", 
        common: "閃鋅礦", 
        category: "離子晶體", 
        key: "ZnS|Simple|基本單元 (離子對)", 
        tags: ["ZnS", "硫化鋅", "閃鋅礦"] 
    },
    { 
        formula: "ZnS", 
        name: "硫化鋅 (晶體堆積)", 
        common: "閃鋅礦", 
        category: "離子晶體", 
        key: "ZnS|Crystal|晶體堆積 (FCC)", 
        tags: ["ZnS", "硫化鋅", "閃鋅礦", "FCC"] 
    },
    { 
        formula: "CuCl", 
        name: "氯化亞銅 (基本單元)", 
        common: "", 
        category: "離子晶體", 
        key: "CuCl|Simple|基本單元 (離子對)", 
        tags: ["CuCl", "氯化亞銅", "Nantokite"] 
    },
    { 
        formula: "CuCl", 
        name: "氯化亞銅 (晶體堆積)", 
        common: "", 
        category: "離子晶體", 
        key: "CuCl|Crystal|晶體堆積 (FCC)", 
        tags: ["CuCl", "氯化亞銅", "FCC"] 
    },
    { 
        formula: "TiO2", 
        name: "二氧化鈦 (基本單元)", 
        common: "金紅石", 
        category: "離子晶體", 
        key: "TiO2|Simple|基本單元", 
        tags: ["TiO2", "二氧化鈦", "金紅石"] 
    },
    { 
        formula: "TiO2", 
        name: "二氧化鈦 (晶體堆積)", 
        common: "金紅石", 
        category: "離子晶體", 
        key: "TiO2|Crystal|晶體堆積 (Tetragonal)", 
        tags: ["TiO2", "二氧化鈦", "金紅石", "四方晶系"] 
    },
    { 
        formula: "Cu2O", 
        name: "氧化亞銅 (基本單元)", 
        common: "赤銅礦", 
        category: "離子晶體", 
        key: "Cu2O|Simple|基本單元", 
        tags: ["Cu2O", "氧化亞銅", "赤銅礦"] 
    },
    { 
        formula: "Cu2O", 
        name: "氧化亞銅 (晶體堆積)", 
        common: "赤銅礦", 
        category: "離子晶體", 
        key: "Cu2O|Crystal|晶體堆積 (Cubic)", 
        tags: ["Cu2O", "氧化亞銅", "赤銅礦", "立方晶系"] 
    },

    // --- 金屬晶體 (依堆積方式分類) ---
    { formula: "Li", name: "鋰", common: "", category: "金屬晶體", key: "Li|鋰", tags: ["Li", "鋰", "BCC"] },
    { formula: "Na", name: "鈉", common: "", category: "金屬晶體", key: "Na|鈉", tags: ["Na", "鈉", "BCC"] },
    { formula: "K", name: "鉀", common: "", category: "金屬晶體", key: "K|鉀", tags: ["K", "鉀", "BCC"] },
    { formula: "Rb", name: "銣", common: "", category: "金屬晶體", key: "Rb", tags: ["Rb", "銣", "BCC"] },
    { formula: "Cs", name: "銫", common: "", category: "金屬晶體", key: "Cs", tags: ["Cs", "銫", "BCC"] },
    { formula: "Be", name: "鈹", common: "", category: "金屬晶體", key: "Be", tags: ["Be", "鈹", "HCP"] },
    { formula: "Mg", name: "鎂", common: "", category: "金屬晶體", key: "Mg", tags: ["Mg", "鎂", "HCP"] },
    { formula: "Ca", name: "鈣", common: "", category: "金屬晶體", key: "Ca", tags: ["Ca", "鈣", "FCC"] },
    { formula: "Sr", name: "鍶", common: "", category: "金屬晶體", key: "Sr", tags: ["Sr", "鍶", "FCC"] },
    { formula: "Ba", name: "鋇", common: "", category: "金屬晶體", key: "Ba", tags: ["Ba", "鋇", "BCC"] },
    { formula: "Po", name: "釙", common: "", category: "金屬晶體", key: "Po", tags: ["Po", "釙", "SC"] },
    { formula: "Fe", name: "鐵 (α)", common: "", category: "金屬晶體", key: "Fe|鐵 (α)", tags: ["Fe", "鐵", "BCC"] },
    { formula: "Cu", name: "銅", common: "", category: "金屬晶體", key: "Cu", tags: ["Cu", "銅", "FCC"] },
    { formula: "Ag", name: "銀", common: "", category: "金屬晶體", key: "Ag", tags: ["Ag", "銀", "FCC"] },
    { formula: "Au", name: "金", common: "", category: "金屬晶體", key: "Au", tags: ["Au", "金", "FCC"] },
    { formula: "Al", name: "鋁", common: "", category: "金屬晶體", key: "Al", tags: ["Al", "鋁", "FCC"] },
    { formula: "Zn", name: "鋅", common: "", category: "金屬晶體", key: "Zn", tags: ["Zn", "鋅", "HCP"] },
    { formula: "Ti", name: "鈦", common: "", category: "金屬晶體", key: "Ti", tags: ["Ti", "鈦", "HCP"] },

    // --- 同核雙原子分子與離子 ---
    { formula: "H2", name: "氫氣", common: "氫", category: "雙原子分子", key: "H2|氫氣|氫", tags: ["H2", "氫氣", "氫"] },
    { formula: "N2", name: "氮氣", common: "氮", category: "雙原子分子", key: "N2|氮氣|氮", tags: ["N2", "氮氣", "氮"] },
    { formula: "O2", name: "氧氣", common: "氧", category: "雙原子分子", key: "O2|氧氣|氧", tags: ["O2", "氧氣", "氧"] },
    { formula: "F2", name: "氟氣", common: "氟", category: "雙原子分子", key: "F2|氟氣|氟", tags: ["F2", "氟氣", "氟"] },
    { formula: "Cl2", name: "氯氣", common: "氯", category: "雙原子分子", key: "Cl2|氯氣|氯", tags: ["Cl2", "氯氣", "氯"] },
    { formula: "Br2", name: "溴", common: "", category: "雙原子分子", key: "Br2|溴", tags: ["Br2", "溴"] },
    { formula: "I2", name: "碘", common: "", category: "雙原子分子", key: "I2|碘", tags: ["I2", "碘"] },
    { formula: "O22-", name: "過氧根離子", common: "", category: "離子", key: "O22-|過氧根離子", tags: ["O22-", "過氧根"] },
    { formula: "C22-", name: "碳化物離子", common: "", category: "離子", key: "C22-|碳化物離子", tags: ["C22-", "碳化物"] },

    // --- 異核雙原子分子與離子 ---
    { formula: "CO", name: "一氧化碳", common: "", category: "雙原子分子", key: "CO|一氧化碳", tags: ["CO", "一氧化碳"] },
    { formula: "NO", name: "一氧化氮", common: "", category: "雙原子分子", key: "NO|一氧化氮", tags: ["NO", "一氧化氮"] },
    { formula: "CN-", name: "氰離子", common: "氰根", category: "離子", key: "CN-|氰根|氰離子", tags: ["CN-", "氰離子", "氰根"] },

// --- 第二段：常見無機分子與鹵化物系列 ---
    // --- 氫化物系列 (來源 [1-5]) ---
    { 
        formula: "CH4", 
        name: "甲烷", 
        common: "天然氣", 
        category: "無機分子", 
        key: "CH4|甲烷", 
        tags: ["CH4", "甲烷", "Methane", "Td"] 
    },
    { 
        formula: "SiH4", 
        name: "矽烷", 
        common: "", 
        category: "無機分子", 
        key: "SiH4|矽烷", 
        tags: ["SiH4", "矽烷", "Silane", "Td"] 
    },
    { 
        formula: "NH3", 
        name: "氨", 
        common: "氨氣", 
        category: "無機分子", 
        key: "NH3|氨|氨氣", 
        tags: ["NH3", "氨", "氨氣", "Ammonia", "C3v"] 
    },
    { 
        formula: "NH4+", 
        name: "銨根離子", 
        common: "銨離子", 
        category: "陽離子", 
        key: "NH4+|銨根離子|銨離子|銨根", 
        tags: ["NH4+", "銨根", "銨離子", "Td"] 
    },
    { 
        formula: "NH2-", 
        name: "胺基陰離子", 
        common: "胺基負離子", 
        category: "陰離子", 
        key: "NH2-|胺基陰離子|胺基負離子", 
        tags: ["NH2-", "胺基", "胺基負離子", "C2v"] 
    },
    { 
        formula: "PH3", 
        name: "磷化氫", 
        common: "", 
        category: "無機分子", 
        key: "PH3|磷化氫", 
        tags: ["PH3", "磷化氫", "Phosphine", "C3v"] 
    },
    { 
        formula: "PH4+", 
        name: "鏻離子", 
        common: "", 
        category: "陽離子", 
        key: "PH4+|鏻離子", 
        tags: ["PH4+", "鏻離子", "Td"] 
    },
    { 
        formula: "H2O", 
        name: "水", 
        common: "水分子", 
        category: "無機分子", 
        key: "H2O|水|水分子", 
        tags: ["H2O", "水", "水分子", "C2v"] 
    },
    { 
        formula: "H3O+", 
        name: "水合氫離子", 
        common: "鋞離子", 
        category: "陽離子", 
        key: "H3O+|水合氫離子|鋞離子", 
        tags: ["H3O+", "水合氫離子", "鋞離子", "C3v"] 
    },
    { 
        formula: "OH-", 
        name: "氫氧根", 
        common: "氫氧根離子", 
        category: "陰離子", 
        key: "OH-|氫氧根|氫氧根離子", 
        tags: ["OH-", "氫氧根", "氫氧根離子", "Cinfv"] 
    },
    { 
        formula: "H2S", 
        name: "硫化氫", 
        common: "氫硫酸", 
        category: "無機分子", 
        key: "H2S|硫化氫|氫硫酸", 
        tags: ["H2S", "硫化氫", "氫硫酸", "C2v"] 
    },
    { 
        formula: "HS-", 
        name: "硫氫根", 
        common: "", 
        category: "陰離子", 
        key: "HS-|硫氫根", 
        tags: ["HS-", "硫氫根", "Cinfv"] 
    },

    // --- 鹵化物系列 (來源 [6-11] 迴圈生成) ---
    // 硼系列
    { formula: "BF3", name: "三氟化硼", common: "", category: "無機分子", key: "BF3|三氟化硼", tags: ["BF3", "三氟化硼", "D3h"] },
    { formula: "BCl3", name: "三氯化硼", common: "", category: "無機分子", key: "BCl3|三氯化硼", tags: ["BCl3", "三氯化硼", "D3h"] },
    { formula: "BBr3", name: "三溴化硼", common: "", category: "無機分子", key: "BBr3|三溴化硼", tags: ["BBr3", "三溴化硼", "D3h"] },
    { formula: "BI3", name: "三碘化硼", common: "", category: "無機分子", key: "BI3|三碘化硼", tags: ["BI3", "三碘化硼", "D3h"] },
    // 鋁系列
    { formula: "AlF3", name: "三氟化鋁", common: "", category: "無機分子", key: "AlF3|三氟化鋁", tags: ["AlF3", "三氟化鋁", "D3h"] },
    { formula: "AlCl3", name: "三氯化鋁", common: "", category: "無機分子", key: "AlCl3|三氯化鋁", tags: ["AlCl3", "三氯化鋁", "D3h"] },
    { formula: "AlBr3", name: "三溴化鋁", common: "", category: "無機分子", key: "AlBr3|三溴化鋁", tags: ["AlBr3", "三溴化鋁", "D3h"] },
    { formula: "AlI3", name: "三碘化鋁", common: "", category: "無機分子", key: "AlI3|三碘化鋁", tags: ["AlI3", "三碘化鋁", "D3h"] },
    // 碳系列
    { formula: "CF4", name: "四氟化碳", common: "四氟甲烷", category: "無機分子", key: "CF4|四氟化碳|四氟甲烷", tags: ["CF4", "四氟化碳", "Td"] },
    { formula: "CCl4", name: "四氯化碳", common: "四氯甲烷", category: "無機分子", key: "CCl4|四氯化碳|四氯甲烷", tags: ["CCl4", "四氯化碳", "Td"] },
    { formula: "CBr4", name: "四溴化碳", common: "四溴甲烷", category: "無機分子", key: "CBr4|四溴化碳|四溴甲烷", tags: ["CBr4", "四溴化碳", "Td"] },
    { formula: "CI4", name: "四碘化碳", common: "四碘甲烷", category: "無機分子", key: "CI4|四碘化碳|四碘甲烷", tags: ["CI4", "四碘化碳", "Td"] },
    // 矽系列
    { formula: "SiF4", name: "四氟化矽", common: "", category: "無機分子", key: "SiF4|四氟化矽", tags: ["SiF4", "四氟化矽", "Td"] },
    { formula: "SiCl4", name: "四氯化矽", common: "", category: "無機分子", key: "SiCl4|四氯化矽|Silicon Tetrachloride", tags: ["SiCl4", "四氯化矽", "Td"] },
    { formula: "SiBr4", name: "四溴化矽", common: "", category: "無機分子", key: "SiBr4|四溴化矽", tags: ["SiBr4", "四溴化矽", "Td"] },
    { formula: "SiI4", name: "四碘化矽", common: "", category: "無機分子", key: "SiI4|四碘化矽", tags: ["SiI4", "四碘化矽", "Td"] },
    // 氮系列
    { formula: "NF3", name: "三氟化氮", common: "", category: "無機分子", key: "NF3|三氟化氮", tags: ["NF3", "三氟化氮", "C3v"] },
    { formula: "NCl3", name: "三氯化氮", common: "", category: "無機分子", key: "NCl3|三氯化氮", tags: ["NCl3", "三氯化氮", "C3v"] },
    { formula: "NBr3", name: "三溴化氮", common: "", category: "無機分子", key: "NBr3|三溴化氮", tags: ["NBr3", "三溴化氮", "C3v"] },
    { formula: "NI3", name: "三碘化氮", common: "", category: "無機分子", key: "NI3|三碘化氮", tags: ["NI3", "三碘化氮", "C3v"] },
    // 磷系列
    { formula: "PF3", name: "三氟化磷", common: "", category: "無機分子", key: "PF3|三氟化磷", tags: ["PF3", "三氟化磷", "C3v"] },
    { formula: "PCl3", name: "三氯化磷", common: "", category: "無機分子", key: "PCl3|三氯化磷|Phosphorus Trichloride", tags: ["PCl3", "三氯化磷", "C3v"] },
    { formula: "PBr3", name: "三溴化磷", common: "", category: "無機分子", key: "PBr3|三溴化磷", tags: ["PBr3", "三溴化磷", "C3v"] },
    { formula: "PI3", name: "三碘化磷", common: "", category: "無機分子", key: "PI3|三碘化磷", tags: ["PI3", "三碘化磷", "C3v"] },
    // 氧系列
    { formula: "OF2", name: "二氟化氧", common: "", category: "無機分子", key: "OF2|二氟化氧", tags: ["OF2", "二氟化氧", "C2v"] },
    { formula: "OCl2", name: "二氯化氧", common: "", category: "無機分子", key: "OCl2|二氯化氧", tags: ["OCl2", "二氯化氧", "C2v"] },
    { formula: "OBr2", name: "二溴化氧", common: "", category: "無機分子", key: "OBr2|二溴化氧", tags: ["OBr2", "二溴化氧", "C2v"] },
    { formula: "OI2", name: "二碘化氧", common: "", category: "無機分子", key: "OI2|二碘化氧", tags: ["OI2", "二碘化氧", "C2v"] },
    // 硫系列
    { formula: "SF2", name: "二氟化硫", common: "", category: "無機分子", key: "SF2|二氟化硫", tags: ["SF2", "二氟化硫", "C2v"] },
    { formula: "SCl2", name: "二氯化硫", common: "", category: "無機分子", key: "SCl2|二氯化硫", tags: ["SCl2", "二氯化硫", "C2v"] },
    { formula: "SBr2", name: "二溴化硫", common: "", category: "無機分子", key: "SBr2|二溴化硫", tags: ["SBr2", "二溴化硫", "C2v"] },
    { formula: "SI2", name: "二碘化硫", common: "", category: "無機分子", key: "SI2|二碘化硫", tags: ["SI2", "二碘化硫", "C2v"] },

// --- 第三段：特殊共振離子、擴大八隅體與無機陰離子群 ---
    // --- 具共振結構之離子與特殊分子 ---
    { formula: "SCN-", name: "硫氰酸根 (主要共振)", common: "N=C=S", category: "共振結構", key: "SCN-|主要共振結構 (N=C=S)", tags: ["SCN-", "硫氰酸根", "Cinfv"] },
    { formula: "SCN-", name: "硫氰酸根 (次要共振)", common: "N≡C-S", category: "共振結構", key: "SCN-|次要共振結構 (N≡C-S)", tags: ["SCN-", "硫氰酸根", "Cinfv"] },
    { formula: "NO+", name: "亞硝鎓離子", common: "", category: "陽離子", key: "NO+|亞硝鎓離子", tags: ["NO+", "亞硝鎓", "Cinfv"] },
    { formula: "NO2+", name: "硝鎓離子", common: "", category: "陽離子", key: "NO2+|硝鎓離子", tags: ["NO2+", "硝鎓", "Dinfh"] },
    { formula: "N3-", name: "疊氮根 (主要共振1)", common: "N=N=N", category: "共振結構", key: "N3-|主要共振結構 (N=N=N)", tags: ["N3-", "疊氮根", "Dinfh"] },
    { formula: "N3-", name: "疊氮根 (主要共振2)", common: "N≡N-N", category: "共振結構", key: "N3-|主要共振結構 (N≡N-N)", tags: ["N3-", "疊氮根", "Dinfh"] },
    { formula: "OCN-", name: "氰酸根 (主要共振)", common: "N≡C-O", category: "共振結構", key: "OCN-|主要共振結構 (N≡C-O)", tags: ["OCN-", "氰酸根", "Cinfv"] },
    { formula: "OCN-", name: "氰酸根 (次要共振)", common: "N=C=O", category: "共振結構", key: "OCN-|次要共振結構 (N=C=O)", tags: ["OCN-", "氰酸根", "Cinfv"] },
    { formula: "CNO-", name: "雷酸根 (主要共振)", common: "C≡N-O", category: "共振結構", key: "CNO-|主要共振結構 (C≡N-O)", tags: ["CNO-", "雷酸根", "Cinfv"] },
    { formula: "CNO-", name: "雷酸根 (次要共振)", common: "C=N=O", category: "共振結構", key: "CNO-|次要共振結構 (C=N=O)", tags: ["CNO-", "雷酸根", "Cinfv"] },
    { formula: "HOCN", name: "氰酸", common: "", category: "無機分子", key: "HOCN|氰酸", tags: ["HOCN", "氰酸", "Cs"] },

    // --- 擴大八隅體分子 (五、六、七配位) ---
    { formula: "PCl5", name: "五氯化磷", common: "", category: "擴大八隅體", key: "PCl5|五氯化磷", tags: ["PCl5", "五氯化磷", "D3h"] },
    { formula: "PBr5", name: "五溴化磷", common: "", category: "擴大八隅體", key: "PBr5|五溴化磷", tags: ["PBr5", "五溴化磷", "D3h"] },
    { formula: "SF6", name: "六氟化硫", common: "", category: "擴大八隅體", key: "SF6|六氟化硫", tags: ["SF6", "六氟化硫", "Oh"] },
    { formula: "SF4", name: "四氟化硫", common: "", category: "擴大八隅體", key: "SF4|四氟化硫", tags: ["SF4", "四氟化硫", "C2v"] },
    { formula: "ClF3", name: "三氟化氯", common: "", category: "擴大八隅體", key: "ClF3|三氟化氯", tags: ["ClF3", "三氟化氯", "C2v"] },
    { formula: "XeF2", name: "二氟化氙", common: "", category: "擴大八隅體", key: "XeF2|二氟化氙", tags: ["XeF2", "二氟化氙", "Dinfh"] },
    { formula: "XeF4", name: "四氟化氙", common: "", category: "擴大八隅體", key: "XeF4|四氟化氙", tags: ["XeF4", "四氟化氙", "D4h"] },
    { formula: "BrF5", name: "五氟化溴", common: "", category: "擴大八隅體", key: "BrF5|五氟化溴", tags: ["BrF5", "五氟化溴", "C4v"] },
    { formula: "IF7", name: "七氟化碘", common: "", category: "擴大八隅體", key: "IF7|七氟化碘", tags: ["IF7", "七氟化碘", "D5h"] },
    { formula: "SeF6", name: "六氟化硒", common: "", category: "擴大八隅體", key: "SeF6|六氟化硒", tags: ["SeF6", "六氟化硒", "Oh"] },
    { formula: "TeF6", name: "六氟化碲", common: "", category: "擴大八隅體", key: "TeF6|六氟化碲", tags: ["TeF6", "六氟化碲", "Oh"] },
    { formula: "AsF5", name: "五氟化砷", common: "", category: "擴大八隅體", key: "AsF5|五氟化砷", tags: ["AsF5", "五氟化砷", "D3h"] },
    { formula: "TeF4", name: "四氟化碲", common: "", category: "擴大八隅體", key: "TeF4|四氟化碲", tags: ["TeF4", "四氟化碲", "C2v"] },
    { formula: "XeO3", name: "三氧化氙", common: "", category: "擴大八隅體", key: "XeO3|三氧化氙", tags: ["XeO3", "三氧化氙", "C3v"] },
    { formula: "XeO4", name: "四氧化氙", common: "", category: "擴大八隅體", key: "XeO4|四氧化氙", tags: ["XeO4", "四氧化氙", "Td"] },
    { formula: "XeOF4", name: "四氟氧化氙", common: "XeOF4", category: "擴大八隅體", key: "XeOF4|四氟氧化氙|XeOF4", tags: ["XeOF4", "四氟氧化氙", "C4v"] },
    { formula: "IOF5", name: "五氟氧化碘", common: "", category: "擴大八隅體", key: "IOF5|五氟氧化碘", tags: ["IOF5", "五氟氧化碘", "C4v"] },
    { formula: "AsF3", name: "三氟化砷", common: "", category: "無機分子", key: "AsF3|三氟化砷", tags: ["AsF3", "三氟化砷", "C3v"] },
    { formula: "SbCl3", name: "三氯化銻", common: "", category: "無機分子", key: "SbCl3|三氯化銻", tags: ["SbCl3", "三氯化銻", "C3v"] },
    { formula: "ICl3", name: "三氯化碘", common: "Iodine Trichloride", category: "擴大八隅體", key: "ICl3|三氯化碘|Iodine Trichloride", tags: ["ICl3", "三氯化碘", "C2v"] },

    // --- 特殊配合物與陰離子群 ---
    { formula: "B2H6", name: "乙硼烷", common: "Diborane", category: "配合物", key: "B2H6|乙硼烷|Diborane", tags: ["B2H6", "乙硼烷", "D2h"] },
    { formula: "B(OH)3", name: "硼酸", common: "", category: "無機分子", key: "B(OH)3|硼酸", tags: ["B(OH)3", "硼酸", "C3h"] },
    { formula: "SiF62-", name: "六氟矽酸根", common: "", category: "陰離子", key: "SiF62-|六氟矽酸根", tags: ["SiF62-", "六氟矽酸根", "Oh"] },
    { formula: "PF6-", name: "六氟磷酸根", common: "", category: "陰離子", key: "PF6-|六氟磷酸根", tags: ["PF6-", "六氟磷酸根", "Oh"] },
    { formula: "SbF6-", name: "六氟銻酸根", common: "", category: "陰離子", key: "SbF6-|六氟銻酸根", tags: ["SbF6-", "六氟銻酸根", "Oh"] },
    { formula: "I3-", name: "三碘錯離子", common: "三碘陰離子", category: "陰離子", key: "I3-|三碘陰離子|三碘錯離子", tags: ["I3-", "三碘陰離子", "Dinfh"] },
    { formula: "ICl2-", name: "二氯碘離子", common: "", category: "陰離子", key: "ICl2-|二氯碘離子", tags: ["ICl2-", "二氯碘離子", "Dinfh"] },
    { formula: "ICl4-", name: "四氯碘離子", common: "", category: "陰離子", key: "ICl4-|四氯碘離子", tags: ["ICl4-", "四氯碘離子", "D4h"] },
    { formula: "BF4-", name: "四氟硼酸根", common: "", category: "陰離子", key: "BF4-|四氟硼酸根", tags: ["BF4-", "四氟硼酸根", "Td"] },
    { formula: "AlCl4-", name: "四氯鋁酸根", common: "", category: "陰離子", key: "AlCl4-|四氯鋁酸根", tags: ["AlCl4-", "四氯鋁酸根", "Td"] },
    { formula: "BH4-", name: "硼氫化離子", common: "", category: "陰離子", key: "BH4-|硼氫化離子", tags: ["BH4-", "硼氫化離子", "Td"] },

// --- 第四段：含氧酸及其酸根、鹽類系列 ---
    // --- 硫酸系列 (Sulfur Oxoacids) ---
    { formula: "H2SO4", name: "硫酸", common: "工業之母", category: "含氧酸", key: "H2SO4|硫酸", tags: ["H2SO4", "硫酸", "C2"] },
    { formula: "HSO4-", name: "硫酸氫根", common: "", category: "酸根離子", key: "HSO4-|硫酸氫根", tags: ["HSO4-", "硫酸氫根", "Cs"] },
    { formula: "SO42-", name: "硫酸根", common: "", category: "酸根離子", key: "SO42-|硫酸根", tags: ["SO42-", "硫酸根", "Td"] },
    { formula: "NaHSO4", name: "硫酸氫鈉", common: "", category: "含氧酸鹽", key: "NaHSO4|硫酸氫鈉", tags: ["NaHSO4", "硫酸氫鈉", "Cs"] },
    { formula: "KHSO4", name: "硫酸氫鉀", common: "", category: "含氧酸鹽", key: "KHSO4|硫酸氫鉀", tags: ["KHSO4", "硫酸氫鉀", "Cs"] },
    { formula: "CaSO4", name: "硫酸鈣", common: "石膏", category: "含氧酸鹽", key: "CaSO4|硫酸鈣|石膏", tags: ["CaSO4", "硫酸鈣", "石膏", "Td"] },
    { formula: "BaSO4", name: "硫酸鋇", common: "重晶石", category: "含氧酸鹽", key: "BaSO4|硫酸鋇|重晶石", tags: ["BaSO4", "硫酸鋇", "重晶石", "鋇餐", "Td"] },
    { formula: "CuSO4", name: "硫酸銅", common: "", category: "含氧酸鹽", key: "CuSO4|硫酸銅", tags: ["CuSO4", "硫酸銅", "Td"] },
    { formula: "FeSO4", name: "硫酸亞鐵", common: "綠礬", category: "含氧酸鹽", key: "FeSO4|硫酸亞鐵|綠礬", tags: ["FeSO4", "硫酸亞鐵", "綠礬", "Td"] },
    { formula: "ZnSO4", name: "硫酸鋅", common: "皓礬", category: "含氧酸鹽", key: "ZnSO4|硫酸鋅|皓礬", tags: ["ZnSO4", "硫酸鋅", "皓礬", "Td"] },
    { formula: "MgSO4", name: "硫酸鎂", common: "瀉鹽", category: "含氧酸鹽", key: "MgSO4|硫酸鎂|瀉鹽", tags: ["MgSO4", "硫酸鎂", "瀉鹽", "Td"] },
    { formula: "H2SO3", name: "亞硫酸", common: "", category: "含氧酸", key: "H2SO3|亞硫酸", tags: ["H2SO3", "亞硫酸", "Cs"] },
    { formula: "HSO3-", name: "亞硫酸氫根", common: "", category: "酸根離子", key: "HSO3-|亞硫酸氫根", tags: ["HSO3-", "亞硫酸氫根", "Cs"] },
    { formula: "SO32-", name: "亞硫酸根", common: "", category: "酸根離子", key: "SO32-|亞硫酸根", tags: ["SO32-", "亞硫酸根", "C3v"] },
    { formula: "Na2SO3", name: "亞硫酸鈉", common: "", category: "含氧酸鹽", key: "Na2SO3|亞硫酸鈉", tags: ["Na2SO3", "亞硫酸鈉", "C3v"] },
    { formula: "NaHSO3", name: "亞硫酸氫鈉", common: "", category: "含氧酸鹽", key: "NaHSO3|亞硫酸氫鈉", tags: ["NaHSO3", "亞硫酸氫鈉", "Cs"] },
    { formula: "CaSO3", name: "亞硫酸鈣", common: "", category: "含氧酸鹽", key: "CaSO3|亞硫酸鈣", tags: ["CaSO3", "亞硫酸鈣", "C3v"] },
    { formula: "H2S2O3", name: "硫代硫酸", common: "", category: "含氧酸", key: "H2S2O3|硫代硫酸", tags: ["H2S2O3", "硫代硫酸", "Cs"] },
    { formula: "HS2O3-", name: "硫代硫酸氫根", common: "", category: "酸根離子", key: "HS2O3-|硫代硫酸氫根", tags: ["HS2O3-", "硫代硫酸氫根", "Cs"] },
    { formula: "S2O32-", name: "硫代硫酸根", common: "", category: "酸根離子", key: "S2O32-|硫代硫酸根", tags: ["S2O32-", "硫代硫酸根", "C3v"] },
    { formula: "Na2S2O3", name: "硫代硫酸鈉", common: "大蘇打/海波", category: "含氧酸鹽", key: "Na2S2O3|硫代硫酸鈉|大蘇打|海波", tags: ["Na2S2O3", "硫代硫酸鈉", "海波", "C3v"] },

    // --- 碳酸系列 (Carbonic Oxoacids) ---
    { formula: "H2CO3", name: "碳酸", common: "", category: "含氧酸", key: "H2CO3|碳酸", tags: ["H2CO3", "碳酸", "Cs"] },
    { formula: "HCO3-", name: "碳酸氫根", common: "", category: "酸根離子", key: "HCO3-|碳酸氫根", tags: ["HCO3-", "碳酸氫根", "Cs"] },
    { formula: "CO32-", name: "碳酸根", common: "", category: "酸根離子", key: "CO32-|碳酸根", tags: ["CO32-", "碳酸根", "D3h"] },
    { formula: "CaCO3", name: "碳酸鈣", common: "灰石", category: "含氧酸鹽", key: "CaCO3|碳酸鈣|灰石", tags: ["CaCO3", "碳酸鈣", "灰石", "D3h"] },
    { formula: "MgCO3", name: "碳酸鎂", common: "", category: "含氧酸鹽", key: "MgCO3|碳酸鎂", tags: ["MgCO3", "碳酸鎂", "D3h"] },
    { formula: "Na2CO3", name: "碳酸鈉", common: "蘇打", category: "含氧酸鹽", key: "Na2CO3|碳酸鈉|蘇打", tags: ["Na2CO3", "碳酸鈉", "蘇打", "D3h"] },
    { formula: "K2CO3", name: "碳酸鉀", common: "草木灰", category: "含氧酸鹽", key: "K2CO3|碳酸鉀|草木灰", tags: ["K2CO3", "碳酸鉀", "草木灰", "D3h"] },
    { formula: "NaHCO3", name: "碳酸氫鈉", common: "小蘇打", category: "含氧酸鹽", key: "NaHCO3|碳酸氫鈉|小蘇打", tags: ["NaHCO3", "碳酸氫鈉", "小蘇打", "Cs"] },

    // --- 硝酸系列 (Nitric Oxoacids) ---
    { formula: "HNO3", name: "硝酸", common: "", category: "含氧酸", key: "HNO3|硝酸", tags: ["HNO3", "硝酸", "Cs"] },
    { formula: "NO3-", name: "硝酸根", common: "", category: "酸根離子", key: "NO3-|硝酸根", tags: ["NO3-", "硝酸根", "D3h"] },
    { formula: "KNO3", name: "硝酸鉀", common: "硝石", category: "含氧酸鹽", key: "KNO3|硝酸鉀|硝石", tags: ["KNO3", "硝酸鉀", "硝石", "D3h"] },
    { formula: "NaNO3", name: "硝酸鈉", common: "智利硝石", category: "含氧酸鹽", key: "NaNO3|硝酸鈉|智利硝石", tags: ["NaNO3", "硝酸鈉", "智利硝石", "D3h"] },
    { formula: "AgNO3", name: "硝酸銀", common: "", category: "含氧酸鹽", key: "AgNO3|硝酸銀", tags: ["AgNO3", "硝酸銀", "D3h"] },
    { formula: "Cu(NO3)2", name: "硝酸銅", common: "", category: "含氧酸鹽", key: "Cu(NO3)2|硝酸銅", tags: ["Cu(NO3)2", "硝酸銅", "D3h"] },
    { formula: "HNO2", name: "亞硝酸", common: "", category: "含氧酸", key: "HNO2|亞硝酸", tags: ["HNO2", "亞硝酸", "Cs"] },
    { formula: "NO2-", name: "亞硝酸根", common: "", category: "酸根離子", key: "NO2-|亞硝酸根", tags: ["NO2-", "亞硝酸根", "C2v"] },
    { formula: "NaNO2", name: "亞硝酸鈉", common: "", category: "含氧酸鹽", key: "NaNO2|亞硝酸鈉", tags: ["NaNO2", "亞硝酸鈉", "C2v"] },
    { formula: "KNO2", name: "亞硝酸鉀", common: "", category: "含氧酸鹽", key: "KNO2|亞硝酸鉀", tags: ["KNO2", "亞硝酸鉀", "C2v"] },

    // --- 磷酸系列 (Phosphoric Oxoacids) ---
    { formula: "H3PO4", name: "磷酸", common: "", category: "含氧酸", key: "H3PO4|磷酸", tags: ["H3PO4", "磷酸", "Cs"] },
    { formula: "H2PO4-", name: "磷酸二氫根", common: "", category: "酸根離子", key: "H2PO4-|磷酸二氫根", tags: ["H2PO4-", "磷酸二氫根", "C2v"] },
    { formula: "HPO42-", name: "磷酸氫根", common: "", category: "酸根離子", key: "HPO42-|磷酸氫根", tags: ["HPO42-", "磷酸氫根", "C3v"] },
    { formula: "PO43-", name: "磷酸根", common: "", category: "酸根離子", key: "PO43-|磷酸根", tags: ["PO43-", "磷酸根", "Td"] },
    { formula: "Ca3(PO4)2", name: "磷酸鈣", common: "", category: "含氧酸鹽", key: "Ca3(PO4)2|磷酸鈣", tags: ["Ca3(PO4)2", "磷酸鈣", "Td"] },
    { formula: "Na3PO4", name: "磷酸鈉", common: "", category: "含氧酸鹽", key: "Na3PO4|磷酸鈉", tags: ["Na3PO4", "磷酸鈉", "Td"] },
    { formula: "Ca(H2PO4)2", name: "磷酸二氫鈣", common: "", category: "含氧酸鹽", key: "Ca(H2PO4)2|磷酸二氫鈣", tags: ["Ca(H2PO4)2", "磷酸二氫鈣", "C2v"] },
    { formula: "H3PO3", name: "亞磷酸", common: "", category: "含氧酸", key: "H3PO3|亞磷酸", tags: ["H3PO3", "亞磷酸", "Cs"] },
    { formula: "H2PO3-", name: "亞磷酸氫根", common: "", category: "酸根離子", key: "H2PO3-|亞磷酸氫根", tags: ["H2PO3-", "亞磷酸氫根", "Cs"] },
    { formula: "HPO32-", name: "亞磷酸根", common: "", category: "酸根離子", key: "HPO32-|亞磷酸根", tags: ["HPO32-", "亞磷酸根", "C3v"] },
    { formula: "Na2HPO3", name: "亞磷酸鈉", common: "", category: "含氧酸鹽", key: "Na2HPO3|亞磷酸鈉", tags: ["Na2HPO3", "亞磷酸鈉", "C3v"] },
    { formula: "H3PO2", name: "次磷酸", common: "", category: "含氧酸", key: "H3PO2|次磷酸", tags: ["H3PO2", "次磷酸", "Cs"] },
    { formula: "H2PO2-", name: "次磷酸根", common: "", category: "酸根離子", key: "H2PO2-|次磷酸根", tags: ["H2PO2-", "次磷酸根", "C2v"] },
    { formula: "NaH2PO2", name: "次磷酸鈉", common: "", category: "含氧酸鹽", key: "NaH2PO2|次磷酸鈉", tags: ["NaH2PO2", "次磷酸鈉", "C2v"] },

    // --- 氯/溴/碘含氧酸系列 (Halogen Oxoacids) ---
    { formula: "HClO4", name: "過氯酸", common: "", category: "含氧酸", key: "HClO4|過氯酸", tags: ["HClO4", "過氯酸", "Cs"] },
    { formula: "ClO4-", name: "過氯酸根", common: "", category: "酸根離子", key: "ClO4-|過氯酸根", tags: ["ClO4-", "過氯酸根", "Td"] },
    { formula: "Mg(ClO4)2", name: "過氯酸鎂", common: "乾燥劑", category: "含氧酸鹽", key: "Mg(ClO4)2|過氯酸鎂", tags: ["Mg(ClO4)2", "過氯酸鎂", "Td"] },
    { formula: "KClO4", name: "過氯酸鉀", common: "", category: "含氧酸鹽", key: "KClO4|過氯酸鉀", tags: ["KClO4", "過氯酸鉀", "Td"] },
    { formula: "NH4ClO4", name: "過氯酸銨", common: "AP", category: "含氧酸鹽", key: "NH4ClO4|過氯酸銨", tags: ["NH4ClO4", "過氯酸銨", "AP", "Td"] },
    { formula: "HClO3", name: "氯酸", common: "", category: "含氧酸", key: "HClO3|氯酸", tags: ["HClO3", "氯酸", "Cs"] },
    { formula: "ClO3-", name: "氯酸根", common: "", category: "酸根離子", key: "ClO3-|氯酸根", tags: ["ClO3-", "氯酸根", "C3v"] },
    { formula: "KClO3", name: "氯酸鉀", common: "", category: "含氧酸鹽", key: "KClO3|氯酸鉀", tags: ["KClO3", "氯酸鉀", "C3v"] },
    { formula: "NaClO3", name: "氯酸鈉", common: "", category: "含氧酸鹽", key: "NaClO3|氯酸鈉", tags: ["NaClO3", "氯酸鈉", "C3v"] },
    { formula: "HClO2", name: "亞氯酸", common: "", category: "含氧酸", key: "HClO2|亞氯酸", tags: ["HClO2", "亞氯酸", "Cs"] },
    { formula: "ClO2-", name: "亞氯酸根", common: "", category: "酸根離子", key: "ClO2-|亞氯酸根", tags: ["ClO2-", "亞氯酸根", "C2v"] },
    { formula: "NaClO2", name: "亞氯酸鈉", common: "", category: "含氧酸鹽", key: "NaClO2|亞氯酸鈉", tags: ["NaClO2", "亞氯酸鈉", "C2v"] },
    { formula: "HClO", name: "次氯酸", common: "", category: "含氧酸", key: "HClO|次氯酸", tags: ["HClO", "次氯酸", "Cs"] },
    { formula: "ClO-", name: "次氯酸根", common: "", category: "酸根離子", key: "ClO-|次氯酸根", tags: ["ClO-", "次氯酸根", "Cinfv"] },
    { formula: "NaClO", name: "次氯酸鈉", common: "漂白水", category: "含氧酸鹽", key: "NaClO|次氯酸鈉|漂白水", tags: ["NaClO", "次氯酸鈉", "漂白水", "Cinfv"] },
    { formula: "Ca(ClO)2", name: "次氯酸鈣", common: "漂白粉", category: "含氧酸鹽", key: "Ca(ClO)2|次氯酸鈣|漂白粉", tags: ["Ca(ClO)2", "次氯酸鈣", "漂白粉", "Cinfv"] },
    { formula: "HBrO3", name: "溴酸", common: "", category: "含氧酸", key: "HBrO3|溴酸", tags: ["HBrO3", "溴酸", "Cs"] },
    { formula: "BrO3-", name: "溴酸根", common: "", category: "酸根離子", key: "BrO3-|溴酸根", tags: ["BrO3-", "溴酸根", "C3v"] },
    { formula: "KBrO3", name: "溴酸鉀", common: "", category: "含氧酸鹽", key: "KBrO3|溴酸鉀", tags: ["KBrO3", "溴酸鉀", "C3v"] },
    { formula: "AgBrO3", name: "溴酸銀", common: "", category: "含氧酸鹽", key: "AgBrO3|溴酸銀", tags: ["AgBrO3", "溴酸銀", "C3v"] },
    { formula: "HIO3", name: "碘酸", common: "", category: "含氧酸", key: "HIO3|碘酸", tags: ["HIO3", "碘酸", "Cs"] },
    { formula: "IO3-", name: "碘酸根", common: "", category: "酸根離子", key: "IO3-|碘酸根", tags: ["IO3-", "碘酸根", "C3v"] },
    { formula: "KIO3", name: "碘酸鉀", common: "補碘食鹽", category: "含氧酸鹽", key: "KIO3|碘酸鉀", tags: ["KIO3", "碘酸鉀", "C3v"] },

// --- 第五段：有機分子、苯環衍生物、錯合物與碳簇 ---
    // --- 脂肪族烴類與鹵代烷 ---
    { formula: "CH4", name: "甲烷", common: "天然氣", category: "烷烴", key: "CH4|甲烷", tags: ["CH4", "甲烷", "Td"] },
    { formula: "C2H6", name: "乙烷", common: "", category: "烷烴", key: "C2H6|乙烷", tags: ["C2H6", "乙烷", "D3d"] },
    { formula: "C3H8", name: "丙烷", common: "", category: "烷烴", key: "C3H8|丙烷", tags: ["C3H8", "丙烷", "C2v"] },
    { formula: "C5H12", name: "正戊烷", common: "", category: "烷烴", key: "C5H12|正戊烷", tags: ["C5H12", "正戊烷", "C2h"] },
    { formula: "C5H12", name: "異戊烷", common: "", category: "烷烴", key: "C5H12|異戊烷", tags: ["C5H12", "異戊烷", "Cs"] },
    { formula: "C5H12", name: "新戊烷", common: "", category: "烷烴", key: "C5H12|新戊烷", tags: ["C5H12", "新戊烷", "Td"] },
    { formula: "C2H4", name: "乙烯", common: "", category: "烯烴", key: "C2H4|乙烯", tags: ["C2H4", "乙烯", "D2h"] },
    { formula: "C3H6", name: "丙烯", common: "", category: "烯烴", key: "C3H6|丙烯", tags: ["C3H6", "丙烯", "Cs"] },
    { formula: "C4H8", name: "1-丁烯", common: "", category: "烯烴", key: "C4H8|1-丁烯", tags: ["C4H8", "1-丁烯", "Cs"] },
    { formula: "C4H8", name: "順-2-丁烯", common: "", category: "烯烴", key: "C4H8|順-2-丁烯", tags: ["C4H8", "順-2-丁烯", "C2v"] },
    { formula: "C4H8", name: "反-2-丁烯", common: "", category: "烯烴", key: "C4H8|反-2-丁烯", tags: ["C4H8", "反-2-丁烯", "C2h"] },
    { formula: "C4H8", name: "2-甲基丙烯", common: "", category: "烯烴", key: "C4H8|2-甲基丙烯", tags: ["C4H8", "2-甲基丙烯", "C2v"] },
    { formula: "C3H4", name: "丙二烯", common: "Allene", category: "二烯烴", key: "C3H4|丙二烯|Allene", tags: ["C3H4", "丙二烯", "D2d"] },
    { formula: "C4H6", name: "1,3-丁二烯", common: "", category: "二烯烴", key: "C4H6|1,3-丁二烯", tags: ["C4H6", "1,3-丁二烯", "C2h"] },
    { formula: "C4H6", name: "1,2-丁二烯", common: "", category: "二烯烴", key: "C4H6|1,2-丁二烯", tags: ["C4H6", "1,2-丁二烯", "Cs"] },
    { formula: "C2H2", name: "乙炔", common: "", category: "炔烴", key: "C2H2|乙炔", tags: ["C2H2", "乙炔", "Dinfh"] },
    { formula: "C4H6", name: "2-丁炔", common: "", category: "炔烴", key: "C4H6|2-丁炔", tags: ["C4H6", "2-丁炔", "D3h"] },
    { formula: "C4H6", name: "1-丁炔", common: "", category: "炔烴", key: "C4H6|1-丁炔", tags: ["C4H6", "1-丁炔", "Cs"] },
    { formula: "C3H6", name: "環丙烷", common: "", category: "環烷烴", key: "C3H6|環丙烷", tags: ["C3H6", "環丙烷", "D3h"] },
    { formula: "C4H8", name: "環丁烷", common: "", category: "環烷烴", key: "C4H8|環丁烷", tags: ["C4H8", "環丁烷", "D2d"] },
    { formula: "C4H8", name: "甲基環丙烷", common: "", category: "環烷烴", key: "C4H8|甲基環丙烷", tags: ["C4H8", "甲基環丙烷", "Cs"] },
    { formula: "C4H6", name: "1-甲基環丙烯", common: "", category: "環烯烴", key: "C4H6|1-甲基環丙烯", tags: ["C4H6", "1-甲基環丙烯", "Cs"] },
    { formula: "C4H6", name: "3-甲基環丙烯", common: "", category: "環烯烴", key: "C4H6|3-甲基環丙烯", tags: ["C4H6", "3-甲基環丙烯", "Cs"] },
    { formula: "C4H6", name: "雙環丁烷", common: "", category: "環烷烴", key: "C4H6|雙環丁烷", tags: ["C4H6", "雙環丁烷", "C2v"] },
    { formula: "C4H6", name: "環丁烯", common: "", category: "環烯烴", key: "C4H6|環丁烯", tags: ["C4H6", "環丁烯", "C2v"] },
    { formula: "CH3Cl", name: "一氯甲烷", common: "氯甲烷", category: "鹵代烷", key: "CH3Cl|一氯甲烷|氯甲烷", tags: ["CH3Cl", "氯甲烷", "C3v"] },
    { formula: "CH2Cl2", name: "二氯甲烷", common: "", category: "鹵代烷", key: "CH2Cl2|二氯甲烷", tags: ["CH2Cl2", "二氯甲烷", "C2v"] },
    { formula: "CHCl3", name: "三氯甲烷", common: "氯仿", category: "鹵代烷", key: "CHCl3|三氯甲烷|氯仿", tags: ["CHCl3", "氯仿", "C3v"] },
    { formula: "CCl4", name: "四氯化碳", common: "", category: "鹵代烷", key: "CCl4|四氯化碳", tags: ["CCl4", "四氯化碳", "Td"] },
    { formula: "C2H5Cl", name: "氯乙烷", common: "", category: "鹵代烷", key: "C2H5Cl|氯乙烷", tags: ["C2H5Cl", "氯乙烷", "Cs"] },
    { formula: "C2H3Cl", name: "氯乙烯", common: "", category: "鹵代烯", key: "C2H3Cl|氯乙烯", tags: ["C2H3Cl", "氯乙烯", "Cs"] },
    { formula: "C2H4Cl2", name: "1,1-二氯乙烷", common: "", category: "鹵代烷", key: "C2H4Cl2|1,1-二氯乙烷", tags: ["C2H4Cl2", "1,1-二氯乙烷", "Cs"] },
    { formula: "C2H4Cl2", name: "1,2-二氯乙烷", common: "", category: "鹵代烷", key: "C2H4Cl2|1,2-二氯乙烷", tags: ["C2H4Cl2", "1,2-二氯乙烷", "C2h"] },
    { formula: "C2H2Cl2", name: "順-1,2-二氯乙烯", common: "", category: "鹵代烯", key: "C2H2Cl2|順-1,2-二氯乙烯", tags: ["C2H2Cl2", "順-1,2-二氯乙烯", "C2v"] },
    { formula: "C2H2Cl2", name: "反-1,2-二氯乙烯", common: "", category: "鹵代烯", key: "C2H2Cl2|反-1,2-二氯乙烯", tags: ["C2H2Cl2", "反-1,2-二氯乙烯", "C2h"] },
    { formula: "C2H2Cl2", name: "1,1-二氯乙烯", common: "", category: "鹵代烯", key: "C2H2Cl2|1,1-二氯乙烯", tags: ["C2H2Cl2", "1,1-二氯乙烯", "C2v"] },
    { formula: "C3H7Cl", name: "1-氯丙烷", common: "", category: "鹵代烷", key: "C3H7Cl|1-氯丙烷", tags: ["C3H7Cl", "1-氯丙烷", "Cs"] },
    { formula: "C3H7Cl", name: "2-氯丙烷", common: "", category: "鹵代烷", key: "C3H7Cl|2-氯丙烷", tags: ["C3H7Cl", "2-氯丙烷", "Cs"] },
    { formula: "C3H6Cl2", name: "1,1-二氯丙烷", common: "", category: "鹵代烷", key: "C3H6Cl2|1,1-二氯丙烷", tags: ["C3H6Cl2", "1,1-二氯丙烷", "Cs"] },
    { formula: "C3H6Cl2", name: "1,2-二氯丙烷", common: "", category: "鹵代烷", key: "C3H6Cl2|1,2-二氯丙烷", tags: ["C3H6Cl2", "1,2-二氯丙烷", "C1"] },
    { formula: "C3H6Cl2", name: "1,3-二氯丙烷", common: "", category: "鹵代烷", key: "C3H6Cl2|1,3-二氯丙烷", tags: ["C3H6Cl2", "1,3-二氯丙烷", "C2v"] },
    { formula: "C3H6Cl2", name: "2,2-二氯丙烷", common: "", category: "鹵代烷", key: "C3H6Cl2|2,2-二氯丙烷", tags: ["C3H6Cl2", "2,2-二氯丙烷", "C2v"] },
    { formula: "C2H2Cl4", name: "1,1,2,2-四氯乙烷", common: "", category: "鹵代烷", key: "C2H2Cl4|1,1,2,2-四氯乙烷", tags: ["C2H2Cl4", "1,1,2,2-四氯乙烷", "C2h"] },
    { formula: "C2H2Cl4", name: "1,1,1,2-四氯乙烷", common: "", category: "鹵代烷", key: "C2H2Cl4|1,1,1,2-四氯乙烷", tags: ["C2H2Cl4", "1,1,1,2-四氯乙烷", "Cs"] },

    // --- 醇、醚、醛、酮、酸、酯、胺、醯胺 ---
    { formula: "CH3OH", name: "甲醇", common: "木精", category: "醇類", key: "CH3OH|甲醇|木精", tags: ["CH3OH", "甲醇", "木精", "Cs"] },
    { formula: "C2H5OH", name: "乙醇", common: "酒精", category: "醇類", key: "C2H5OH|乙醇|Ethanol|酒精", tags: ["C2H5OH", "乙醇", "酒精", "Cs"] },
    { formula: "C3H8O", name: "1-丙醇", common: "", category: "醇類", key: "C3H8O|1-丙醇", tags: ["C3H8O", "1-丙醇", "Cs"] },
    { formula: "C3H8O", name: "2-丙醇", common: "", category: "醇類", key: "C3H8O|2-丙醇", tags: ["C3H8O", "2-丙醇", "Cs"] },
    { formula: "C2H4(OH)2", name: "乙二醇", common: "1,2-乙二醇", category: "醇類", key: "C2H4(OH)2|乙二醇|1,2-乙二醇", tags: ["C2H4(OH)2", "乙二醇", "C2"] },
    { formula: "C3H5(OH)3", name: "丙三醇", common: "甘油", category: "醇類", key: "C3H5(OH)3|丙三醇|甘油", tags: ["C3H5(OH)3", "甘油", "C1"] },
    { formula: "CH3OCH3", name: "甲醚", common: "二甲醚", category: "醚類", key: "CH3OCH3|甲醚|二甲醚", tags: ["CH3OCH3", "甲醚", "C2v"] },
    { formula: "C3H8O", name: "甲乙醚", common: "", category: "醚類", key: "C3H8O|甲乙醚", tags: ["C3H8O", "甲乙醚", "Cs"] },
    { formula: "C2H5CHO", name: "丙醛", common: "", category: "醛類", key: "C2H5CHO|丙醛", tags: ["C2H5CHO", "丙醛", "Cs"] },
    { formula: "CHOCHO", name: "乙二醛", common: "Glyoxal", category: "醛類", key: "CHOCHO|乙二醛|Glyoxal", tags: ["CHOCHO", "乙二醛", "C2h"] },
    { formula: "CH3COCH3", name: "丙酮", common: "", category: "酮類", key: "CH3COCH3|丙酮", tags: ["CH3COCH3", "丙酮", "C2v"] },
    { formula: "HCOOH", name: "甲酸", common: "蟻酸", category: "羧酸", key: "HCOOH|甲酸|蟻酸", tags: ["HCOOH", "甲酸", "蟻酸", "Cs"] },
    { formula: "H2C2O4", name: "乙二酸", common: "草酸", category: "羧酸", key: "H2C2O4|乙二酸|草酸", tags: ["H2C2O4", "草酸", "C2h"] },
    { formula: "C4H4O4", name: "順丁烯二酸", common: "", category: "羧酸", key: "C4H4O4|順丁烯二酸", tags: ["C4H4O4", "順丁烯二酸", "C2v"] },
    { formula: "C4H4O4", name: "反丁烯二酸", common: "", category: "羧酸", key: "C4H4O4|反丁烯二酸", tags: ["C4H4O4", "反丁烯二酸", "C2h"] },
    { formula: "CH3COOCH3", name: "乙酸甲酯", common: "Methyl Acetate", category: "酯類", key: "CH3COOCH3|乙酸甲酯|Methyl Acetate", tags: ["CH3COOCH3", "乙酸甲酯", "Cs"] },
    { formula: "CH3COOC2H5", name: "乙酸乙酯", common: "Ethyl Acetate", category: "酯類", key: "CH3COOC2H5|乙酸乙酯|Ethyl Acetate", tags: ["CH3COOC2H5", "乙酸乙酯", "Cs"] },
    { formula: "CH3NH2", name: "甲胺", common: "甲基胺", category: "胺類", key: "CH3NH2|甲胺|甲基胺", tags: ["CH3NH2", "甲胺", "Cs"] },
    { formula: "CH3NHCH3", name: "二甲胺", common: "Dimethylamine", category: "胺類", key: "CH3NHCH3|二甲胺|Dimethylamine", tags: ["CH3NHCH3", "二甲胺", "Cs"] },
    { formula: "N(CH3)3", name: "三甲胺", common: "Trimethylamine", category: "胺類", key: "N(CH3)3|三甲胺|Trimethylamine", tags: ["N(CH3)3", "三甲胺", "C3v"] },
    { formula: "HCONH2", name: "甲醯胺", common: "Formamide", category: "醯胺", key: "HCONH2|甲醯胺|Formamide", tags: ["HCONH2", "甲醯胺", "Cs"] },
    { formula: "CH3CONH2", name: "乙醯胺", common: "Acetamide", category: "醯胺", key: "CH3CONH2|乙醯胺|Acetamide", tags: ["CH3CONH2", "乙醯胺", "Cs"] },
    { formula: "CO(NH2)2", name: "尿素", common: "", category: "醯胺", key: "CO(NH2)2|尿素", tags: ["CO(NH2)2", "尿素", "C2v"] },
    { formula: "CH3NO2", name: "硝基甲烷", common: "", category: "有機分子", key: "CH3NO2|硝基甲烷", tags: ["CH3NO2", "硝基甲烷", "Cs"] },
    { formula: "CH3CN", name: "乙腈", common: "氰甲烷", category: "有機分子", key: "CH3CN|乙腈|氰甲烷", tags: ["CH3CN", "乙腈", "C3v"] },
    { formula: "C3H3N", name: "丙烯腈", common: "Acrylonitrile", category: "有機分子", key: "C3H3N|丙烯腈|Acrylonitrile", tags: ["C3H3N", "丙烯腈", "Cs"] },

    // --- 醣類 ---
    { formula: "C6H12O6", name: "半乳糖", common: "", category: "醣類", key: "C6H12O6|半乳糖", tags: ["C6H12O6", "半乳糖", "C1"] },
    { formula: "C6H12O6", name: "葡萄糖", common: "", category: "醣類", key: "C6H12O6|葡萄糖", tags: ["C6H12O6", "葡萄糖", "C1"] },
    { formula: "C6H12O6", name: "果糖", common: "", category: "醣類", key: "C6H12O6|果糖", tags: ["C6H12O6", "果糖", "C1"] },

    // --- 芳香烴與衍生物 ---
    { formula: "C6H6", name: "苯", common: "Benzene", category: "芳香烴", key: "C6H6|苯|Benzene", tags: ["C6H6", "苯", "D6h"] },
    { formula: "C6H5CH3", name: "甲苯", common: "Toluene", category: "芳香烴", key: "C6H5CH3|甲苯|C7H8|Toluene", tags: ["C6H5CH3", "甲苯", "Cs"] },
    { formula: "C8H10", name: "乙苯", common: "Ethylbenzene", category: "芳香烴", key: "C8H10|乙苯|Ethylbenzene", tags: ["C8H10", "乙苯", "Cs"] },
    { formula: "C8H10", name: "鄰二甲苯", common: "o-Xylene", category: "芳香烴", key: "C8H10|鄰二甲苯|o-Xylene", tags: ["C8H10", "鄰二甲苯", "C2v"] },
    { formula: "C8H10", name: "間二甲苯", common: "m-Xylene", category: "芳香烴", key: "C8H10|間二甲苯|m-Xylene", tags: ["C8H10", "間二甲苯", "C2v"] },
    { formula: "C8H10", name: "對二甲苯", common: "p-Xylene", category: "芳香烴", key: "C8H10|對二甲苯|p-Xylene", tags: ["C8H10", "對二甲苯", "D2h"] },
    { formula: "C8H8", name: "苯乙烯", common: "Styrene", category: "芳香烴", key: "C8H8|苯乙烯|Styrene", tags: ["C8H8", "苯乙烯", "Cs"] },
    { formula: "C10H8", name: "萘", common: "Naphthalene", category: "芳香烴", key: "C10H8|萘|Naphthalene", tags: ["C10H8", "萘", "D2h"] },
    { formula: "C16H10", name: "芘", common: "", category: "芳香烴", key: "C16H10|芘", tags: ["C16H10", "芘", "D2h"] },
    { formula: "C22H14", name: "稠五苯", common: "", category: "芳香烴", key: "C22H14|稠五苯", tags: ["C22H14", "稠五苯", "D2h"] },
    { formula: "C6H5OH", name: "苯酚", common: "石炭酸", category: "酚類", key: "C6H5OH|(苯)酚|酚|石炭酸", tags: ["C6H5OH", "苯酚", "Cs"] },
    { formula: "C6H5NH2", name: "苯胺", common: "胺苯", category: "胺類", key: "C6H5NH2|苯胺|胺苯", tags: ["C6H5NH2", "苯胺", "Cs"] },
    { formula: "C6H5COOH", name: "苯甲酸", common: "安息香酸", category: "羧酸", key: "C6H5COOH|苯甲酸|安息香酸", tags: ["C6H5COOH", "苯甲酸", "Cs"] },
    { formula: "C6H5SO3H", name: "苯磺酸", common: "", category: "有機酸", key: "C6H5SO3H|苯磺酸", tags: ["C6H5SO3H", "苯磺酸", "Cs"] },
    { formula: "C6H5NO2", name: "硝基苯", common: "", category: "芳香烴衍生物", key: "C6H5NO2|硝基苯", tags: ["C6H5NO2", "硝基苯", "C2v"] },
    { formula: "C6H5Cl", name: "氯苯", common: "", category: "芳香烴衍生物", key: "C6H5Cl|氯苯", tags: ["C6H5Cl", "氯苯", "C2v"] },
    { formula: "C6H5Br", name: "溴苯", common: "", category: "芳香烴衍生物", key: "C6H5Br|溴苯", tags: ["C6H5Br", "溴苯", "C2v"] },
    { formula: "C6H4Cl2", name: "鄰二氯苯", common: "1,2-Dichlorobenzene", category: "芳香烴衍生物", key: "C6H4Cl2|鄰二氯苯|1,2-Dichlorobenzene", tags: ["C6H4Cl2", "鄰二氯苯", "C2v"] },
    { formula: "C6H4Cl2", name: "間二氯苯", common: "1,3-Dichlorobenzene", category: "芳香烴衍生物", key: "C6H4Cl2|間二氯苯|1,3-Dichlorobenzene", tags: ["C6H4Cl2", "間二氯苯", "C2v"] },
    { formula: "C6H4Cl2", name: "對二氯苯", common: "1,4-Dichlorobenzene", category: "芳香烴衍生物", key: "C6H4Cl2|對二氯苯|1,4-Dichlorobenzene", tags: ["C6H4Cl2", "對二氯苯", "D2h"] },
    { formula: "C7H6O3", name: "鄰羥基苯甲酸", common: "水楊酸", category: "羧酸", key: "C7H6O3|鄰羥基苯甲酸|Salicylic Acid|水楊酸|柳酸", tags: ["C7H6O3", "水楊酸", "柳酸", "Cs"] },
    { formula: "C9H8O4", name: "阿斯匹靈", common: "乙醯水楊酸", category: "酯類", key: "C9H8O4|阿斯匹靈|乙醯柳酸|乙醯水楊酸", tags: ["C9H8O4", "阿斯匹靈", "乙醯水楊酸", "C1"] },
    { formula: "C8H9NO2", name: "乙醯胺基苯酚", common: "普拿疼", category: "醯胺", key: "C8H9NO2|乙醯胺基苯酚|普拿疼", tags: ["C8H9NO2", "普拿疼", "Cs"] },
    { formula: "C8H9NO", name: "乙醯胺苯", common: "乙醯苯胺", category: "醯胺", key: "C8H9NO|乙醯胺苯|乙醯苯胺", tags: ["C8H9NO", "乙醯苯胺", "C1"] },
    { formula: "C7H5(NO2)3", name: "三硝基甲苯", common: "TNT", category: "有機分子", key: "C7H5(NO2)3|三硝基甲苯|TNT|2,4,6-三硝基甲苯", tags: ["C7H5(NO2)3", "TNT", "三硝基甲苯", "Cs"] },
    { formula: "C6H6Cl6", name: "六氯環己烷(γ)", common: "六氯化苯", category: "鹵代烴", key: "C6​H6​Cl6​|1,2,3,4,5,6-六氯環己烷(γ)|六氯化苯", tags: ["C6H6Cl6", "六氯環己烷", "六氯化苯", "Cs"] },
    { formula: "C12H18O6", name: "六甲氧基苯", common: "", category: "芳香烴衍生物", key: "C12H18O6|六甲氧基苯|1,2,3,4,5,6-hexamethoxybenzene", tags: ["C12H18O6", "六甲氧基苯", "C6h"] },
    { formula: "C10H15N", name: "甲基苯丙胺", common: "安非他命", category: "有機分子", key: "C10H15N|甲基苯丙胺|Methamphetamine", tags: ["C10H15N", "甲基苯丙胺", "C1"] },
    { formula: "Fe(C5H5)2", name: "二茂鐵", common: "Ferrocene", category: "錯合物", key: "Fe(C5H5)2|二茂鐵|Ferrocene", tags: ["Fe(C5H5)2", "二茂鐵", "D5h"] },

    // --- 簡單二元離子化合物 ---
    { formula: "KCl", name: "氯化鉀", common: "", category: "鹽類", key: "KCl|氯化鉀", tags: ["KCl", "氯化鉀"] },
    { formula: "KI", name: "碘化鉀", common: "", category: "鹽類", key: "KI|碘化鉀", tags: ["KI", "碘化鉀"] },
    { formula: "KBr", name: "溴化鉀", common: "", category: "鹽類", key: "KBr|溴化鉀", tags: ["KBr", "溴化鉀"] },
    { formula: "NaF", name: "氟化鈉", common: "", category: "鹽類", key: "NaF|氟化鈉", tags: ["NaF", "氟化鈉"] },
    { formula: "LiF", name: "氟化鋰", common: "", category: "鹽類", key: "LiF|氟化鋰", tags: ["LiF", "氟化鋰"] },
    { formula: "MgO", name: "氧化鎂", common: "苦土", category: "氧化物", key: "MgO|氧化鎂|苦土", tags: ["MgO", "氧化鎂"] },
    { formula: "CaO", name: "氧化鈣", common: "生石灰", category: "氧化物", key: "CaO|氧化鈣|生石灰", tags: ["CaO", "氧化鈣"] },
    { formula: "BaO", name: "氧化鋇", common: "", category: "氧化物", key: "BaO|氧化鋇", tags: ["BaO", "氧化鋇"] },
    { formula: "ZnO", name: "氧化鋅", common: "鋅白", category: "氧化物", key: "ZnO|氧化鋅|鋅白", tags: ["ZnO", "氧化鋅"] },
    { formula: "CuO", name: "氧化銅", common: "", category: "氧化物", key: "CuO|氧化銅", tags: ["CuO", "氧化銅"] },
    { formula: "AgCl", name: "氯化銀", common: "", category: "鹽類", key: "AgCl|氯化銀", tags: ["AgCl", "氯化銀"] },
    { formula: "AgBr", name: "溴化銀", common: "", category: "鹽類", key: "AgBr|溴化銀", tags: ["AgBr", "溴化銀"] },
    { formula: "AgI", name: "碘化銀", common: "", category: "鹽類", key: "AgI|碘化銀", tags: ["AgI", "碘化銀"] },
    { formula: "NaH", name: "氫化鈉", common: "", category: "氫化物", key: "NaH|氫化鈉", tags: ["NaH", "氫化鈉"] },
    { formula: "HgS", name: "硫化汞", common: "硃砂", category: "硫化物", key: "HgS|硫化汞|硃砂", tags: ["HgS", "硫化汞"] },
    { formula: "MgCl2", name: "氯化鎂", common: "", category: "鹽類", key: "MgCl2|氯化鎂", tags: ["MgCl2", "氯化鎂"] },
    { formula: "CaCl2", name: "氯化鈣", common: "", category: "鹽類", key: "CaCl2|氯化鈣", tags: ["CaCl2", "氯化鈣"] },
    { formula: "CaF2", name: "氟化鈣", common: "螢石", category: "鹽類", key: "CaF2|氟化鈣|螢石", tags: ["CaF2", "氟化鈣"] },
    { formula: "BaCl2", name: "氯化鋇", common: "", category: "鹽類", key: "BaCl2|氯化鋇", tags: ["BaCl2", "氯化鋇"] },
    { formula: "CuCl2", name: "氯化銅", common: "", category: "鹽類", key: "CuCl2|氯化銅", tags: ["CuCl2", "氯化銅"] },
    { formula: "PbI2", name: "碘化鉛", common: "黃金雨", category: "鹽類", key: "PbI2|碘化鉛", tags: ["PbI2", "碘化鉛"] },
    { formula: "CaH2", name: "氫化鈣", common: "", category: "氫化物", key: "CaH2|氫化鈣", tags: ["CaH2", "氫化鈣"] },
    { formula: "Na2O", name: "氧化鈉", common: "", category: "氧化物", key: "Na2O|氧化鈉", tags: ["Na2O", "氧化鈉"] },
    { formula: "K2O", name: "氧化鉀", common: "", category: "氧化物", key: "K2O|氧化鉀", tags: ["K2O", "氧化鉀"] },
    { formula: "Na2S", name: "硫化鈉", common: "臭鹼", category: "硫化物", key: "Na2S|硫化鈉", tags: ["Na2S", "硫化鈉"] },
    { formula: "FeCl2", name: "氯化亞鐵", common: "", category: "鹽類", key: "FeCl2|氯化亞鐵", tags: ["FeCl2", "氯化亞鐵"] },
    { formula: "FeCl3", name: "氯化鐵", common: "", category: "鹽類", key: "FeCl3|氯化鐵", tags: ["FeCl3", "氯化鐵"] },
    { formula: "AlCl3", name: "氯化鋁", common: "", category: "鹽類", key: "AlCl3|氯化鋁", tags: ["AlCl3", "氯化鋁"] },
    { formula: "Al2O3", name: "氧化鋁", common: "剛玉", category: "氧化物", key: "Al2O3|氧化鋁|剛玉", tags: ["Al2O3", "氧化鋁"] },
    { formula: "Fe2O3", name: "氧化鐵", common: "赤鐵礦", category: "氧化物", key: "Fe2O3|氧化鐵|赤鐵礦", tags: ["Fe2O3", "氧化鐵"] },

    // --- 碳簇與其他分子 ---
    { formula: "P4", name: "白磷", common: "黃磷", category: "無機分子", key: "P4|白磷|黃磷|White Phosphorus", tags: ["P4", "白磷", "Td"] },
    { formula: "P4O6", name: "六氧化四磷", common: "", category: "無機分子", key: "P4O6|六氧化四磷|Phosphorus Hexoxide", tags: ["P4O6", "Td"] },
    { formula: "P4O10", name: "十氧化四磷", common: "", category: "無機分子", key: "P4O10|十氧化四磷|Phosphorus Pentoxide", tags: ["P4O10", "Td"] },
    { formula: "S8", name: "斜方硫", common: "硫磺", category: "無機分子", key: "S8|斜方硫|單斜硫|硫磺", tags: ["S8", "硫磺", "D4d"] },
    { formula: "H2O2", name: "過氧化氫", common: "雙氧水", category: "無機分子", key: "H2O2|過氧化氫|雙氧水", tags: ["H2O2", "雙氧水", "C2"] },
    { formula: "H2S2", name: "二硫化氫", common: "", category: "無機分子", key: "H2S2|二硫化氫", tags: ["H2S2", "C2"] },
    { formula: "S2Cl2", name: "二氯化二硫", common: "二氯化硫", category: "無機分子", key: "S2Cl2|二氯化二硫|二氯化硫", tags: ["S2Cl2", "C2"] },
    { formula: "N2O3", name: "三氧化二氮", common: "", category: "無機分子", key: "N2O3|三氧化二氮", tags: ["N2O3", "Cs"] },
    { formula: "N2O4", name: "四氧化二氮", common: "", category: "無機分子", key: "N2O4|四氧化二氮", tags: ["N2O4", "D2h"] },
    { formula: "N2O5", name: "五氧化二氮", common: "", category: "無機分子", key: "N2O5|五氧化二氮", tags: ["N2O5", "C2"] },
    { formula: "C60", name: "碳60", common: "富勒烯", category: "碳簇", key: "C60|碳六十|碳60|富勒烯|足球烯", tags: ["C60", "富勒烯", "足球烯", "Ih"] },
    { formula: "C36", name: "碳36", common: "", category: "碳簇", key: "C36|碳36", tags: ["C36", "碳36"] },
    { formula: "C40", name: "碳40", common: "", category: "碳簇", key: "C40|碳40", tags: ["C40", "碳40"] },
    { formula: "C50", name: "碳50", common: "", category: "碳簇", key: "C50|碳50", tags: ["C50", "碳50"] },
    { formula: "C70", name: "碳70", common: "", category: "碳簇", key: "C70|碳70", tags: ["C70", "碳70"] },
    { formula: "C80", name: "碳80", common: "", category: "碳簇", key: "C80|碳80", tags: ["C80", "碳80"] },
    { formula: "C100", name: "碳100", common: "", category: "碳簇", key: "C100|碳100", tags: ["C100", "碳100"] }
];
